languages:
    python: true
engines:
    pep8:
        enabled: true
    radon: 
        enabled: true
    duplication:
        enabled: true
        config:
            languages:
                - python
ratings:
    paths:
        - pipsalabim/**/*
exclude_paths:
    - tests/**/*
    - docs/**/* 