sudo: required
services: docker
dist: bionic
group: edge
language: python
matrix:
    include:
        - python: "3.5"
          env: TOXENV=py35
        - python: "3.6"
          env: TOXENV=py36
        - python: "3.8"
          env: TOXENV=py38
        - python: "3.7"
          env: TOXENV=py37
        - python: "pypy3"
          env: TOXENV=pypy3
install:
    - pip install -r requirements-dev.txt
script:
    - tox -e ${TOXENV}
    - |
        if [ "${TOXENV}" == "pypy3" ]; then
          docker run -v ${PWD}:${PWD} -w ${PWD} \
              pypy:3 bash -c \
              "pypy3 setup.py install && \
              pypy3 -m pipsalabim.cli update"
        else
          docker run -v ${PWD}:${PWD} -w ${PWD} \
              dockershelf/python:${TRAVIS_PYTHON_VERSION} bash -c \
              "python${TRAVIS_PYTHON_VERSION} setup.py install && \
              python${TRAVIS_PYTHON_VERSION} -m pipsalabim.cli update"
        fi
after_success:
    - coveralls
